version: '3.8'

services:
  # Development configuration for REST API Service
  site-analyzer-rest:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    ports:
      - "5000:5000"
      - "5678:5678"  # For Python debugger
    command: python -m debugpy --listen 0.0.0.0:5678 main_refactored.py rest

  # Development configuration for gRPC Service
  site-analyzer-grpc:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    ports:
      - "50051:50051"
      - "5679:5679"  # For Python debugger
    command: python -m debugpy --listen 0.0.0.0:5679 main_refactored.py grpc

  # Development configuration for CLI Service
  site-analyzer-cli:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
